### ISSUE TITLE
args detected as import ?

### ISSUE THREAD

**Issue by jycouet** [sweepline/eslint-plugin-unused-imports#100]
Hi, 
I'm trying to go to ESLint v9, and started from scratch my config _(not that easy bump)_.

I don't know why but with this config
```ts
rules: {
  'no-unused-vars': 'off',
  '@typescript-eslint/no-unused-vars': 'off',
  'unused-imports/no-unused-imports': 'error',
  'unused-imports/no-unused-vars': 'error',
}
```
I get this error:
![image](https://github.com/user-attachments/assets/7708492b-040b-40b5-a58b-2a391aff0f82)
![image](https://github.com/user-attachments/assets/cf1c0c73-13aa-43e5-922f-6b1eebbc58ff)

I'm expecting to have `unused-imports/no-unused-vars`, but I don't get why I'm getting `unused-imports/no-unused-imports` (same position & variable)
`event` is not an import.

Do you have a default repro template for me to try reproducing it somewhere ?

Thank you for your help.

**Comment by antfu** [comment]
> Do you have a default repro template for me to try reproducing it somewhere ?

Sorry we don't. But I guess it shouldn't be hard to setup a basic node project to reproduce? I think we could not maintain repro template for every single plugin and keep them in sync.

From a glance I can't tell why it would happend. I'd appreciate a repro for us to investigate. Thanks

**Comment by jycouet** [comment]
Thank you for the reply.

I did a repro https://github.com/jycouet/eslint-repro-unused-imports
But was not able to reproduce the issue! :(

I tried to go as close as my "big" repo (growing it step by step): 
- using decorator
- using an external plugin `@kitql/eslint-config` that has `eslint-plugin-unused-imports` configured

On my side, it would be the variable `titi` that triggers `unused-imports/no-unused-imports`. But it's not an import, it's an arg of a function.

I also looked into [ESLint Config Inspector](https://github.com/eslint/config-inspector)[v0.5.4](https://github.com/eslint/config-inspector/releases/tag/v0.5.4) _(thx for this nice tool)_, and was able to explore rules & plugins & co... But didn't find where I'm screwing things.

Would you have an idea of where else should I explore ? 
Is there a way to run the rule in debug mode so that I can trace what's the root cause ? 

Let me know

**Comment by jycouet** [comment]
I started to `console.log` to in the `node_modules/     /index.mjs` to see if I can find something.

And in the "wrong" report, `parent` is null. (In these lines https://github.com/sweepline/eslint-plugin-unused-imports/blob/master/src/rules/predicates.ts#L18-L26)

![image](https://github.com/user-attachments/assets/e22c8d5b-6baf-45d1-8123-8da8bd4764da)

**Comment by antfu** [comment]
I don't know under what circumstances the `parent` would be `null`, but yeah, indeed, there was a bug on our side. Thanks.

**Comment by jycouet** [comment]
Thank you, I'll test it ASAP 👍

**Comment by jycouet** [comment]
Do you know when it will be released?

**Comment by antfu** [comment]
It's released now. There was a release failure I didn't notice before going bed 😅

**Comment by jycouet** [comment]
Haha, thx again ✌️

**Comment by mbrevda** [comment]
Still seeing this on 4.1.4 with the `error` argument on `catch` blocks

**Comment by mbrevda** [comment]
@antfu were you able to have a look?
