### ISSUE TITLE
Allow TypeScript 4

### ISSUE THREAD

**Issue by danvk** [sweepline/eslint-plugin-unused-imports#15]
I noticed that my project had five (FIVE!) different versions of TypeScript in it today. One reason is that this package requires `typescript@^3.6.3`: https://github.com/sweepline/eslint-plugin-unused-imports/blob/f791475babafb980743ea1b9533c90e68cff9b5c/package.json#L24

TypeScript 4.0 [came out](https://devblogs.microsoft.com/typescript/announcing-typescript-4-0/) in August 2020. I'm not aware of backwards-incompatible changes, so it would be nice if `eslint-plugin-unused-imports` allowed TS 4.0.

```
$ yarn list typescript
yarn list v1.22.4
warning ../package.json: No license field
warning Filtering by arguments is deprecated. Please use the pattern option instead.
├─ @mark.probst/typescript-json-schema@0.32.0
│  └─ typescript@3.2.4
├─ eslint-plugin-unused-imports@0.1.3
│  └─ typescript@3.9.7
├─ pg-to-ts@3.5.1
│  └─ typescript@3.9.7
├─ quicktype@15.0.258
│  └─ typescript@3.2.4
└─ typescript@4.0.2
✨  Done in 1.03s.
```

**Comment by sweepline** [comment]
I haven't tested #13 yet, so I'm a bit on the fence with that.
