### ISSUE TITLE
Not all unused imports being stripped

### ISSUE THREAD

**Issue by lochstar** [sweepline/eslint-plugin-unused-imports#2]
Hi,

I'd like to use this plugin in a project I am working on, however I've noticed not all cases are covered. For example the following:

```js
import { foo, bar, baz, boz } from 'foobar';
foo(bar);
```

Results in:

```js
import { foo, bar,  boz } from 'foobar';
```

But should be:

```js
import { foo, bar } from 'foobar';
```

Regards

**Comment by sweepline** [comment]
Works fine for me, the following:
```js
import { foo, bar, baz, boz } from 'foobar';
foo(bar);
```
results in:
```js
import { foo, bar } from "foobar";
foo(bar);
```
when using `eslint --fix`, how did you run Eslint? Eslint needs to run multiple times to function correctly, so f.x. I have noticed you need to save multiple times using the [vscode plugin](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint). This is behaviour of Eslint and not something I can change.
