### ISSUE TITLE
it will ignore Interface

### ISSUE THREAD

**Issue by L-x-C** [sweepline/eslint-plugin-unused-imports#23]
```
import someProps from './someProps'

interface myProps extends someProps {}

export default class Index extends React.Component<myProps,{}>
```

and after run eslint
it will show ` 'someProps' is defined but never used.eslintunused-imports/no-unused-imports`

**Comment by sweepline** [comment]
Interfaces are a typescript thing, you need to use `unused-imports/no-unused-imports-ts`. Notice the `-ts`.

**Comment by L-x-C** [comment]
> Interfaces are a typescript thing, you need to use `unused-imports/no-unused-imports-ts`. Notice the `-ts`.

still the same `'someProps' is defined but never used.eslintunused-imports/no-unused-imports-ts`

**Comment by sweepline** [comment]
I cannot reproduce this, what is your `eslintrc.js`. You must have configured something wrong.

**Comment by L-x-C** [comment]
> I cannot reproduce this, what is your `eslintrc.js`. You must have configured something wrong.

My bad, solved it，thx！
