### ISSUE TITLE
Error: Cannot find module '@typescript-eslint/eslint-plugin'

### ISSUE THREAD

**Issue by nadnoslen** [sweepline/eslint-plugin-unused-imports#25]
Odd error in my EmberJs app that uses this linter.  Dependabot just upgraded me from `1.0.1` to `1.0.3` and linting fails to load with the following error:

```
Error: Failed to load plugin 'unused-imports' declared in '.eslintrc.js': Cannot find module '@typescript-eslint/eslint-plugin'
```

I've got no direct dependencies to Typescript in this project.  My `.eslintrc.js` is just bringing in the unused-imports plugin and setting these rules:

```javascript
'use strict';

module.exports = {
  // ...
  plugins: ['ember', 'ember-suave', 'prettier', 'unused-imports'],
  // ...
  rules: {
    // ...
    'unused-imports/no-unused-imports': 2,
    'unused-imports/no-unused-vars': 1,
  },
```

Let me know if this information helps or if there's something I can do to help out.

**Comment by enjoylife** [comment]
Seeing the same _(I'm using flow)_. Its breaking because there is no conditional import on the ts specific rules,
```
module.exports.rules = requireIndex(__dirname + "/rules");
```

therefore its pulling in `no-unused-imports-ts.js`, which requires the package `@typescript-eslint/eslint-plugin`.  And if your outside of the ts library package ecosystem you are not going to have it.

**Comment by sweepline** [comment]
Thanks, I'll fix this ASAP. It is because I sent from pulling in typescript-eslint to having it as a peer dependency.

**Comment by DelliriumX** [comment]
> Thanks, I'll fix this ASAP. It is because I changed from pulling in typescript-eslint to having it as a peer dependency.

Thank you. This has been a livign nightmare since i last updated, I am not too good at the whole underlaying infrastructure and I couldnt for the death of me figgure out what I did wrong.

**Comment by sweepline** [comment]
I have changed the plugin to use typescript only if needed, this also removes the `-ts` rules.
Could you please confirm it works by replacing the dependency version on your `package.json` with:
```
    "eslint-plugin-unused-imports": "sweepline/eslint-plugin-unused-imports#master"
```

**Comment by DelliriumX** [comment]
> I have changed the plugin to use typescript only if needed, this also removes the `-ts` rules.
> Could you please confirm it works by replacing the dependency version on your `package.json` with:
> 
> ```
>     "eslint-plugin-unused-imports": "sweepline/eslint-plugin-unused-imports#master"
> ```

I can confirm this works (or to be precise, doesn't throw the error anymore) when tested in my environment, not sure about the OP's.

**Comment by sweepline** [comment]
Thanks

**Comment by nadnoslen** [comment]
Awesome!  Thanks @sweepline!!
