### ISSUE TITLE
Any way to disable fix, but showing the issue as warning or error?

### ISSUE THREAD

**Issue by jeffrson** [sweepline/eslint-plugin-unused-imports#26]
Hi,

is there any way to disable just the fixer? I'd like to see the error or warning, but don't want my editor (VSCode) to remove imports when  saving (because I know I'll need it later).

Thanks

**Comment by sweepline** [comment]
Just run eslint without the `--fix` flag. This is more a question for the eslint people than this package.

**Comment by jeffrson** [comment]
> This is more a question for the eslint people than this package.

Not really.

As I already wrote, it's a matter of editor integration which executes fixes when saving. And I do want to fix issues, but while developing, saving often, some fixes shouldn't be applied that deeply change sources (like changing 'let' to 'const' or deleting imports).

There are discussions in vscode-eslint and eslint - usually shifting responsibility. It's a pity you're playing the same game. Why shouldn't it be possible to add a parameter like "no-autofix" or don't fix warnings?

**Comment by sweepline** [comment]
I'm not sure I understand? Is it because this is the only rule you do not want autofixed?

**Comment by jeffrson** [comment]
Yes.

Well, ideally it should work like https://github.com/aladdin-add/eslint-plugin/tree/master/packages/no-autofix - showing all errors and warnings, but don't fix it. Unfortunately, no-autofix doesn't work for non-core-eslint-rules.

So I thought a new option for this rule might be the simplest and most compatible solution.

Sorry if this wasn't clear from the beginning.
