### ISSUE TITLE
The immediate following comments get removed when the unused import got removed

### ISSUE THREAD

**Issue by Amber-Song** [sweepline/eslint-plugin-unused-imports#28]
Hey, I encountered a situation that when an unused import is removed, the immediate following comments also get removed, like this.

`
import Button from '/src/components/button' // unused import

// This component is navigation

export default class nav(props) {
  // Other code
}
`

After remove the unused import, it looks like
`
export default class nav(props) {
  // Other code
}
`

I wonder if any other people also have a similar problem. And is there anyone knows what cause it? Is it because I config something wrong or that is because of other things?

And this is the config file:
`
module.exports = {
  root: true,
  parser: '@typescript-eslint/parser',
  plugins: ['@typescript-eslint', 'react', 'jsx-a11y', 'unused-imports'],
  extends: [
    'eslint:recommended',
    'plugin:@typescript-eslint/eslint-recommended',
    'plugin:@typescript-eslint/recommended',
    'plugin:react/recommended',
    'plugin:jsx-a11y/recommended',
  ],
  env: {
    browser: true,
    node: true,
    es6: true,
  },
  rules: {
    ...
    'no-unused-vars': 'warn', // or '@typescript-eslint/no-unused-vars': 'warn',
    'unused-imports/no-unused-imports': 'error',
    'unused-imports/no-unused-vars': 'warn',
    ...
  },
};
`

Thanks a lot!

**Comment by sweepline** [comment]
I think this is because the comments are not part of the AST when using ESLint. I got other requests to remove the line after the unused import also, I'll see if I can satisfy both things or make a config for this.

**Comment by hepter** [comment]
![image](https://user-images.githubusercontent.com/14141071/111777471-64bce280-88c4-11eb-8fac-af3f275c73ac.png)
Although the problem I have with me is not the same, it looks a bit similar.

**Comment by Amber-Song** [comment]
> I think this is because the comments are not part of the AST when using ESLint. I got other requests to remove the line after the unused import also, I'll see if I can satisfy both things or make a config for this.

Thank you so much!

**Comment by Amber-Song** [comment]
> though the problem I have with me is not the same, it looks a bit similar.
> Probably it deletes everything

Yeah. I think it is the same problem.
