### ISSUE TITLE
TypeError: Cannot read property 'type' of null

### ISSUE THREAD

**Issue by FritsvanCampen** [sweepline/eslint-plugin-unused-imports#29]
I get the error

> TypeError: Cannot read property 'type' of null

on some `.js` files that don't use import (uses require instead). I'm not entirely sure what triggers this code path but I think it doesn't matter because the fix is so trivial.

The problem is that on this line https://github.com/sweepline/eslint-plugin-unused-imports/blob/25465bdb3822af0183c8c8cb423ac6c399d68f9b/lib/rules/predicates.js#L6 `parent` is `null`.

Suggested fix: add a check if `parent` is `null` and `return false`.

Update: I figured out what the condition is that triggers this code path:

Declare a `global` with `/*global foo*/` and then don't use foo in the file. This is technically an unused import but I wouldn't expect this library to pick it up.

**Comment by sweepline** [comment]
Thanks, this was very helpful.
