### ISSUE TITLE
Is this incompatible with eslint 6.8?

### ISSUE THREAD

**Issue by trajano** [sweepline/eslint-plugin-unused-imports#37]
Expo at present is still on `eslint 6.8` I don't really see any problems using the plugin, but it is annoying to see the peer dependency warning.  I just want to confirm whether there's something specific to eslint 7.x that this plugin requires.

**Comment by sweepline** [comment]
No i dont think so. I should change the dependency to `^6.0.0 || ^7.0.0`, thanks.
