### ISSUE TITLE
ESLint v8 Compatibility?

### ISSUE THREAD

**Issue by gfyoung** [sweepline/eslint-plugin-unused-imports#38]
With `@typescript-eslint/*` now compatible with `v8`, this seems feasible now with `package.json` updates and this:

https://gist.github.com/lydell/d62ce96c95c035811133a5396195da14

PS: it would be nice to have this plugin formally included in the `eslint` rules instead of inheriting from `unused-vars`.

The `--fix` functionality included is very useful!

I imagine you already considered this but mentioning it just in case.

**Comment by AndysonDK** [comment]
+1
