### ISSUE TITLE
Version 2 does not work with Node.js v15

### ISSUE THREAD

**Issue by bennycode** [sweepline/eslint-plugin-unused-imports#40]
I wanted to upgrade from eslint-plugin-unused-imports v1.1.5 to v2.0.0 but it fails in my CI environment using Node.js v15.14.0 with the following message:

> error eslint-plugin-unused-imports@2.0.0: The engine "node" is incompatible with this module. Expected version "^12.22.0 || ^14.17.0 || >=16.0.0". Got "15.14.0"

Why did you exclude Node v15 here? https://github.com/sweepline/eslint-plugin-unused-imports/blob/master/package.json#L37-L39

**Comment by sweepline** [comment]
This was copied from eslint 8 itself, which has this node requirement.
Check https://github.com/eslint/eslint/blob/main/package.json

**Comment by sweepline** [comment]
Eslint dropped version 15 as it is neither LTS or the current node version. See https://nodejs.org/en/about/releases/, you should be using v16 if you want LTS or v17 if you want the current branch.
