### ISSUE TITLE
Autofix doesn't work with .js files

### ISSUE THREAD

**Issue by mishabruml** [sweepline/eslint-plugin-unused-imports#47]
Running `eslint src/migrations/1656172476541-migration.js` yields: 
```
src/migrations/1656172476541-migration.js
  1:9   error  'MigrationInterface' is assigned a value but never used. Allowed unused vars must match /^_/u  unused-imports/no-unused-vars
  1:29  error  'QueryRunner' is assigned a value but never used. Allowed unused vars must match /^_/u         unused-imports/no-unused-vars

✖ 2 problems (2 errors, 0 warnings)
```

So the rule is definitely detecting the error. VSCode applies syntax highlighting too, so all is working as expected as far as detection goes.
<img width="501" alt="Screenshot 2022-06-25 at 17 13 12" src="https://user-images.githubusercontent.com/25983780/175781904-e6c29eb4-9b0b-47c2-a3bc-6e5dae805935.png">

However, running `eslint --fix src/migrations/1656172476541-migration.js` yields the same error message, but **does not auto-fix the problem.**

I have tested the rule and autofix in the same repository against typescript files and it works without issue.

root eslintrc.json:

```json
{
  "root": true,
  "overrides": [
    // typescript rules...
    {
      "plugins": ["unused-imports"],
      "files": ["*.js"],
      "rules": {
        "quotes": "off",
        "arrow-parens": 0,
        "indent": "off",
        "object-curly-spacing": ["error", "always"]
      }
    }
  ],
  "extends": ["eslint:recommended", "xo"],
  "ignorePatterns": ["dist", "coverage"]
}

```
local eslint.rc (in the migrations dir I want the rule applied to): 
```json
{
  "rules": {
    "no-unused-vars": "off",
    "unused-imports/no-unused-imports": "error",
    "unused-imports/no-unused-vars": [
      "error",
      {
        "vars": "all",
        "varsIgnorePattern": "^_",
        "args": "after-used",
        "argsIgnorePattern": "^_"
      }
    ]
  }
}
```

**Comment by sweepline** [comment]
It does work with JS, just only ES6 module imports as described in the readme. I can't distinguish between a regular const and a require import in the AST so i wont solve this. 

You can see that it is also caught by the `unused-imports/no-unused-vars` rule, not the `unused-imports/no-unused-imports` rule.
