### ISSUE TITLE
Can't get autofixer to work

### ISSUE THREAD

**Issue by wadefleming-nz** [sweepline/eslint-plugin-unused-imports#48]
I have setup a simple project, where an unused variable is detected but not fixed.

**Actual**
1. Clone repo from https://github.com/wadefleming-nz/unused-vars-test
2. `npx eslint --fix index.js`
3. Use of `var` for variable `x` is fixed automatically by changing it to `let` (as per `no-var` rule)
4. Unused variable `unused` in `index.js` is identified, but NOT fixed

**Expected:**
`unused` variable is removed as it is not in used and `--fix` was specified.

Should this work? If yes what am I doing wrong?

Thanks

**Environment:**
 "eslint": "^8.21.0",
 "eslint-plugin-unused-imports": "^2.0.0"

**Comment by sweepline** [comment]
This plugin fixes unused import statements by leveraging the eslint-unused-vars rule. It does not supply an autofixer for variables and other things.

**Comment by corysimmons** [comment]
Posterity: just add `'unused-imports/no-unused-imports': `error`,` to your ESLint config and this plugin will remove unused imports.

**Comment by 1071125093** [comment]
same probolem  
ithe autofixer works for no-unused-imports
not works for no-unused-vars
