### ISSUE TITLE
typescript-eslint v6 support?

### ISSUE THREAD

**Issue by mtripg6666tdr** [sweepline/eslint-plugin-unused-imports#56]
[typescript-eslint v6 is out](https://typescript-eslint.io/blog/announcing-typescript-eslint-v6). Is eslint-plugin-unused-imports going to support typescript-eslint v6?
Simply updating `@typescript-eslint/**` causes npm to report a conflicted peer-dependencies error.

**Comment by sweepline** [comment]
Closed by #55
