### ISSUE TITLE
While resolving: eslint-plugin-unused-imports@3.0.0 Found: @typescript-eslint/eslint-plugin@5.62.0

### ISSUE THREAD

**Issue by SamHuo213** [sweepline/eslint-plugin-unused-imports#57]
While installing 

`npm install eslint-plugin-unused-imports --save-dev`

I get the following error

`
npm ERR! While resolving: eslint-plugin-unused-imports@3.0.0
npm ERR! Found: @typescript-eslint/eslint-plugin@5.62.0
npm ERR! node_modules/@typescript-eslint/eslint-plugin
npm ERR!   dev @typescript-eslint/eslint-plugin@"^5.59.11" from the root project
`

![image](https://github.com/sweepline/eslint-plugin-unused-imports/assets/40151580/8defcdbc-0c2c-486a-87ab-25b92f6cdd42)

**Comment by abdosalehpkcs** [comment]
I am facing same issue, latest working version was @typescript-eslint/eslint-plugin@5.60.0 with eslint-plugin-unused-imports@2.0.0

**Comment by alpharder** [comment]
Guys, pay attention to the readme:

```
Version 3.x.x is for eslint 8 with @typescript-eslint/eslint-plugin 6
Version 2.x.x is for eslint 8 with @typescript-eslint/eslint-plugin 5
```

You're both installing incorrect versions

**Comment by kctang** [comment]
My apologies for not rtfm carefully. Given my scenario, switching to v2.x.x works.
