### ISSUE TITLE
Bug: typeScript decorators

### ISSUE THREAD

**Issue by 782042369** [sweepline/eslint-plugin-unused-imports#59]
<img width="1053" alt="image" src="https://github.com/sweepline/eslint-plugin-unused-imports/assets/28727900/4fffda0d-86ad-452b-9631-d18f4e200f0c">
In ESLint, when using the --fix option, it unintentionally removes variables used within TypeScript decorators.

**Comment by sweepline** [comment]
Can you confirm to me that the underlying `@typescript-eslint/no-unused-vars` does not report the imports unused? You can do this by disabling my plugin and enabling the `@typescript-eslint/no-unused-vars` rule.

If the underlying plugin reports them unused, then I can't do anything about it and you should report it to the upstream package.

**Comment by PabloPerezAguilo** [comment]
Same problem.

As @sweepline said  @typescript-eslint/no-unused-vars are reporting like unused.

Probably this bug: [link](https://github.com/typescript-eslint/typescript-eslint/issues/2945)

I fixed upgrading @typescript-eslint/eslint-plugin and @typescript-eslint/parser from 5.3.0 to 6.12.0
