### ISSUE TITLE
For elint globals, eslint incorrectly detected unused

### ISSUE THREAD

**Issue by 14glwu** [sweepline/eslint-plugin-unused-imports#71]
![image](https://github.com/sweepline/eslint-plugin-unused-imports/assets/26249572/d8d4a959-8064-494f-917c-bf0245e88f34)
Expect: no error.
Reality: For eslint globals, eslint incorrectly detected an error
https://eslint.org/docs/latest/use/configure/language-options#specifying-globals

this is my eslint config: 
`
  plugins: ["unused-imports"],
   rules: {
        "no-unused-vars": "off",
        "unused-imports/no-unused-imports": "error",
        "unused-imports/no-unused-vars": [
            "warn",
            {
                "vars": "all",
                "varsIgnorePattern": "^_",
                "args": "after-used",
                "argsIgnorePattern": "^_",
            },
        ],
      }
`

**Comment by sweepline** [comment]
This is most likely an issue upstream, try to see if "no-unused-vars" will also report this error.

**Comment by 14glwu** [comment]
> This is most likely an issue upstream, try to see if "no-unused-vars" will also report this error.

thanks for your reply, I got where problem is. it is just reported by "no-unused-vars" rule
