### ISSUE TITLE
Support Flat Config

### ISSUE THREAD

**Issue by FloEdelmann** [sweepline/eslint-plugin-unused-imports#74]
ESLint v8 already supports the [new "flat" configuration format](https://eslint.org/docs/latest/use/configure/configuration-files-new) and in ESLint v9, it will become the default. It will still be possible to use this plugin then, but it'll require a legacy wrapper. It would be nice if this plugin could add native support for flat config.

Some helpful links:

* https://eslint.org/docs/next/use/configure/migration-guide
* https://github.com/eslint/eslint/issues/18093
* https://typescript-eslint.io/blog/announcing-typescript-eslint-v7/

**Comment by sweepline** [comment]
Flat configs just work with this plugin. Try 
```js
import eslint from '@eslint/js';
import tseslint from 'typescript-eslint';
import unusedImports from "eslint-plugin-unused-imports";

export default tseslint.config(
  eslint.configs.recommended,
  ...tseslint.configs.recommended,
  {
    plugins: {
        "unused-imports": unusedImports
    },
  },
  {
    files: ["**/*.ts", "**/*.tsx"],
    rules: {
        '@typescript-eslint/no-unused-vars': "off",
        'unused-imports/no-unused-vars': [
            'error',
            {
              argsIgnorePattern: '^_',
              varsIgnorePattern: '^_'
            }
          ],
        'unused-imports/no-unused-imports': 'error'
    }
  }
);
```

Or is there something else you want to do?

**Comment by FloEdelmann** [comment]
Oh, you're right, this plugin does not expose any shared configs, so there's nothing to do. Thanks for the fast response :slightly_smiling_face:
