### ISSUE TITLE
eslint 9 support

### ISSUE THREAD

**Issue by hongz1** [sweepline/eslint-plugin-unused-imports#75]
I am wondering when it is going to be compatible with ESLINT 9 since they announced this version officially.

Thanks.

![image](https://github.com/sweepline/eslint-plugin-unused-imports/assets/6565136/d251f4ed-c206-4a22-84db-6bc07371fb83)

**Comment by sweepline** [comment]
As this package also supports @typescript-eslint. Not before https://github.com/typescript-eslint/typescript-eslint/issues/8211 is live.

**Comment by WtfJoke** [comment]
Not sure if you have seen it, but eslint 9 support has been added to `@typescript-eslint`: https://github.com/typescript-eslint/typescript-eslint/issues/8211

**Comment by sweepline** [comment]
Thanks, I will take a look at updating then. This is a package i have mostly written for work reasons and we dont update so often.
