### ISSUE TITLE
Imports are being duplicated

### ISSUE THREAD

**Issue by matsondawson** [sweepline/eslint-plugin-unused-imports#80]
Optimizing imports creates duplicate.
I've removed all the other plugins, and I quite can't figure out what causes the issue.
Attached are before and after examples with my eslint config.
Any ideas?
![image](https://github.com/sweepline/eslint-plugin-unused-imports/assets/1276179/f9890a37-76a0-4ca2-8949-9ac0b97ee69f)

### Features:

├── @typescript-eslint/eslint-plugin@7.8.0
├── @typescript-eslint/parser@7.8.0
├── eslint-plugin-prettier@5.1.3
├── eslint-plugin-react-hooks@4.6.2
├── eslint-plugin-react@7.34.1
├── eslint-plugin-unused-imports@3.2.0
├── eslint@8.57.0

[ZoneFilledPolygon.before.ts.txt](https://github.com/sweepline/eslint-plugin-unused-imports/files/15212132/ZoneFilledPolygon.before.ts.txt)
[ZoneFilledPolygon.after.ts.txt](https://github.com/sweepline/eslint-plugin-unused-imports/files/15212133/ZoneFilledPolygon.after.ts.txt)
[eslintrc.generator.json.txt](https://github.com/sweepline/eslint-plugin-unused-imports/files/15212135/eslintrc.generator.json.txt)

**Comment by matsondawson** [comment]
Now I'm loosing brackes.

[FootprintAttr.before.ts.txt](https://github.com/sweepline/eslint-plugin-unused-imports/files/15212358/FootprintAttr.before.ts.txt)
[FootprintAttr.after.ts.txt](https://github.com/sweepline/eslint-plugin-unused-imports/files/15212359/FootprintAttr.after.ts.txt)

**Comment by sweepline** [comment]
I cannot reproduce this with the files you have provided.
