### ISSUE TITLE
Looking for maintainers?

### ISSUE THREAD

**Issue by sweepline** [sweepline/eslint-plugin-unused-imports#82]
eslint-plugin-unused-imports was a project i first started at my job because we wanted people to not be dependent on [typescript hero](https://marketplace.visualstudio.com/items?itemName=rbbit.typescript-hero). It was a means to an end and it is not the prettiest thing around, but it works! I have always thought it should at least be some kind of optional fix upstream in ESLint, but I never got around to doing the work for them.

As of today I have switched to using [biome](https://biomejs.dev/) at my job because it has all of the capabilities we need in a linter and formatter, but without having to maintain stuff ourselves. This is mainly removing unused imports and sorting imports, but the speed improvements are also great.

So I no longer have as much reason for maintaining this package, and I would recommend other people to try out [biome](https://biomejs.dev/).

I wont stop maintaining this right away, but as eslint changes more this is harder to keep working correctly.

I do not want to create some kind of problematic event by handing this over to the wrong person. It has many dependents and also high-value dependents, so I am at a loss whether to just deprecate it or try to find a maintainer. I would really like for the feature to be upstreamed, and I have requested for them to do so.

Regards, Mikkel.

**Comment by orbiteleven** [comment]
Thanks for all your work on this. 

I hate to threadjack, but I'm interested to hear about your stack and experience moving to Biome. I've been waiting to move our SvelteKit/Typescript stack over until they complete their HTML/Svelte support.

**Comment by SukkaW** [comment]
What about putting the package in a **maintenance mode**?

Here I quote from `rollup-plugin-dts`'s README:

> This project is in _maintenance mode_. That means there will be no more active feature development.
> There will still be occasional releases to maintain compatibility with future TypeScript releases.
> Pull Requests are always welcome, however reaction time on both Issues and PRs can be slow.

**Comment by antfu** [comment]
@sweepline Hey, sorry I didn't see this issue beforehand; as a maintainer, I can relate to your situation a lot and that's completely understandable.

I depend on this plugin a lot and would be very glad to help maintain it or even take over - especially if you are no longer using it yourself. I am ok to be a collaborator on this repo, or if you want to completely get rid of the maintenance, you can also directly transfer the repo and package to me, and I could take care of it.

**Comment by sweepline** [comment]
Thanks @antfu, just adding you as a maintainer in the beginning sounds like a great idea.

**Comment by antfu** [comment]
I have a plan to migrate this repo to typescript and publish dual format ESM/CJS to be future-proof. If you agree on that, I can work on it and send some PRs.

**Comment by sweepline** [comment]
Yeah that sounds great.

**Comment by antfu** [comment]
I guess this can be closed; I will handle the maintenance onwards. Thanks for the trust @sweepline!
