### ISSUE TITLE
Add support for JSX/React?

### ISSUE THREAD

**Issue by swernerx** [sweepline/eslint-plugin-unused-imports#9]
Thanks for this plugin. Very helpful in a large code base.

For our React/JSX-enabled projects it does not seem to work well though.

Do you mind adding support for this?

Example code - reports issues with `LegalLinks`, `DefaultFooter` and `React` which are marked as unused:

```tsx
import React from 'react'

import { DefaultFooter } from '../../lib/Molecules/Footer'
import LegalLinks from '../../lib/Molecules/LegalLinks'

export default () => (
  <DefaultFooter
    copyright={<LegalLinks termsAndConditions={copyright} />}
    links={<LegalLinks termsAndConditions={termsAndConditions} />}
  />
)
```

We might have to track `JSXIdentifier` and its `name` attribute.

<img width="569" alt="Bildschirmfoto 2020-05-04 um 11 10 15" src="https://user-images.githubusercontent.com/145201/80951283-e6fcff00-8df7-11ea-99e5-98ab82e59290.png">

If you do not have resources right now to work on it, please tell us. We might be able to spend some time working on a PR.

**Comment by sweepline** [comment]
Thanks for the well structured issue :) I tested your piece of code, and I can't reproduce, what does your `.eslintrc.js` looks like?

**Comment by swernerx** [comment]
Thanks for getting back quickly.

Here I uploaded a small example config to show the issue: https://github.com/swernerx/eslint-plugin-unused-imports-jsx

**Comment by swernerx** [comment]
That's the output:

> `npx eslint index.js`

```
eslint-test/index.js
  1:8   warning  'React' is defined but never used          unused-imports/no-unused-imports-ts
  3:10  warning  'DefaultFooter' is defined but never used  unused-imports/no-unused-imports-ts
  4:8   warning  'LegalLinks' is defined but never used     unused-imports/no-unused-imports-ts

✖ 3 problems (0 errors, 3 warnings)
  0 errors and 3 warnings potentially fixable with the `--fix` option.
```

**Comment by sweepline** [comment]
Ahh yes, I seem to have forgotten something in the README. You need to use the following two rules for react code to work properly.

```
"react/jsx-uses-react": "warn",
		"react/jsx-uses-vars": "warn",

**Comment by swernerx** [comment]
Thanks! Seems to work! Sorry for the noise :)
