### ISSUE TITLE
Why doesn't eslint-plugin-unused-imports detect an unused exported class?

### ISSUE THREAD

**Issue by jon9090** [sweepline/eslint-plugin-unused-imports#90]
If I have `export class MyClass {}` and I don't import it anywhere in my project, why doesn't [eslint-plugin-unused-imports](https://github.com/sweepline/eslint-plugin-unused-imports) detect it?

```
//foo.ts:
export class MyClass {}
```

**Comment by zymotik** [comment]
This will be very hard to debug without a bit more info. Do you have reproduction steps? Include tsconfig, eslint config and location of the file in your repo.

**Comment by antfu** [comment]
When you export anything, it automatically bails out the unused detection. ESLint is single-file-based analysing, and for such cases it would be hard to detect and not always desired (like if you are writing a library etc.)

I'd say this would be consider out-of-scope. Thanks for bringing up
