### ISSUE TITLE
Regression: plugin cannot be `require`d in v4.1.1 because of extra `default` in CommonJS

### ISSUE THREAD

**Issue by abrahamguo** [sweepline/eslint-plugin-unused-imports#94]
Given `require('eslint-plugin-unused-imports')`, in v4.0.1, this was returned:
```
{
  meta: {},
  configs: {},
  rules: {
    'no-unused-vars': { create: [Function: create], schema: undefined, meta: [Object] },
    'no-unused-imports': { create: [Function: create], schema: undefined, meta: [Object] }
  },
  processors: {}
}
```
However, in v4.1.1, this is returned:
```
{
  default: {
    meta: { name: 'unused-imports' },
    rules: { 'no-unused-vars': [Object], 'no-unused-imports': [Object] }
  }
}
```

This means that v4.1.1 cannot be used with ESLint 8 classic config (whereas v4.0.1 could), because classic config uses `require()` behind the scenes to pull in plugins.
As a result of this, when using v4.1.1 with ESLint classic config, ESLint reports
```
  1:1  error  Definition for rule 'unused-imports/no-unused-imports' was not found  unused-imports/no-unused-imports
  1:1  error  Definition for rule 'unused-imports/no-unused-vars' was not found     unused-imports/no-unused-vars
```

I believe this is an unintentional breaking change for a semver-minor release.

**Comment by Pito1992** [comment]
Oh my god, have installed it in a couple of minutes and found this issue. I temporarily fixed it by changing the eslint extension to json.

**Comment by yunsii** [comment]
https://github.com/sweepline/eslint-plugin-unused-imports/commit/576c77050be6da9ac47eb09fc93c7806dcaa28a7 v4.1.3 is still not released 😂

**Comment by antfu** [comment]
AH, sorry, my bad. Just released.
